### ISSUE TITLE
https://localhost/teams not accessible, getting error

### ISSUE THREAD

**Issue by chechani** [frappe/gameplan#101]
On trying to access gameplan after installation of v14 , getting following error
```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    html = self.render_template()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 232, in render_template
    html = frappe.render_template(self.source, self.context, safe_render=safe_render)
  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template
    return get_jenv().from_string(template).render(context)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 17, in top-level template code
  File "env/lib/python3.10/site-packages/jinja2/filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "env/lib/python3.10/site-packages/jinja2/utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DebugUndefined is not JSON serializable
```

**Comment by netchampfaris** [comment]
I have added local setup instructions, please follow it and let me know if it works for you: https://github.com/frappe/gameplan/commit/f9292ffc8a6c06c01520047bae5822ef5ea909d1

**Comment by ncc-social** [comment]
I went through the local setup instruction and receive only a blank page
<img width="911" alt="image" src="https://user-images.githubusercontent.com/78477962/192394184-0fc3669c-58cc-4c36-b2ce-e8906767a821.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/78477962/192394266-fc279d1d-4a68-4b2a-a66f-3a92be692ab6.png">

**Comment by netchampfaris** [comment]
Just tried on a new site. Works.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9355208/192427371-8cdc2c46-e138-42e1-a801-ac421e863492.png">

Are you sure you have pulled in latest changes?

**Comment by chechani** [comment]
Its opening at url http://localhost/teams/home  , thanks , we can try to understand it
