### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by chechani** [frappe/gameplan#131]
Installing gameplan...
Updating DocTypes for gameplan      : [====================                    ] 50%An error occurred while installing gameplan: Module import failed for Team Discussion, the DocType you're trying to open might be deleted.<br> Error: No module named 'redis.commands'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/gameplan/gameplan/gameplan/doctype/team_discussion/team_discussion.py", line 6, in <module>
    from gameplan.gameplan.doctype.team_discussion.search import update_index
  File "apps/gameplan/gameplan/gameplan/doctype/team_discussion/search.py", line 6, in <module>
    from redis.commands.search.field import TextField, NumericField
ModuleNotFoundError: No module named 'redis.commands'

**Comment by ankush** [comment]
You need `develop` branch as of now... we will figure something out for supporting v14 too.

**Comment by femijoshuao** [comment]
I am still facing issues with it. Not installing. I think the issue is not fixed yet.
