### ISSUE TITLE
not able to upload videos

### ISSUE THREAD

**Issue by harshit-30** [frappe/gameplan#170]
Create a post > upload video > get the following error: 

`FileUploader.8e3cd048.js:1 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 56, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1596, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/handler.py", line 214, in upload_file
    frappe.throw(_("You can only upload JPG, PNG, PDF, TXT or Microsoft documents."))
  File "apps/frappe/frappe/__init__.py", line 524, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 492, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 441, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: You can only upload JPG, PNG, PDF, TXT or Microsoft documents.`

Debugging result: All the users are Website Users.

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/19433
