### ISSUE TITLE
Error while going to Gameplan page

### ISSUE THREAD

**Issue by chechani** [frappe/gameplan#187]
I am getting below error in Gameplan, This is causing issue in not displaying created teams
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 56, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1613, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/gameplan/gameplan/extends/client.py", line 12, in get_list
    query = frappe.qb.engine.get_query(
AttributeError: type object 'MariaDB' has no attribute 'engine'
```
App version
Frappe Drive: v0.0.1 (main)
Frappe Framework: v15.x.x-develop () (develop)
FrappeDesk: v0.5.15 (main)
Gameplan: v0.0.1 (main)

**Comment by netchampfaris** [comment]
Fixed in https://github.com/frappe/gameplan/commit/b8dcd705f8f6dce0dd6766d4038b8cc15efe5bcc#diff-e0206796218d19d2ef2acccdd380d4e949f5fafc15d44d6769ab283225f79676

**Comment by Govind-Jangid** [comment]
@netchampfaris 
Still same error
![image](https://user-images.githubusercontent.com/63184660/216756927-73b10fbc-9955-4d9a-b0a4-75234a246be4.png)
