### ISSUE TITLE
Error: type object 'MariaDB' has no attribute 'engine'

### ISSUE THREAD

**Issue by Govind-Jangid** [frappe/gameplan#201]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 53, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1591, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/gameplan/gameplan/extends/client.py", line 11, in get_list
    query = frappe.qb.engine.get_query(
AttributeError: type object 'MariaDB' has no attribute 'engine'

**Comment by Govind-Jangid** [comment]
https://github.com/frappe/gameplan/issues/187#issue-1556369132

**Comment by ankush** [comment]
not supported on v14.

**Comment by Govind-Jangid** [comment]
![image](https://user-images.githubusercontent.com/63184660/234929327-2000a7fa-8598-4dd2-af2d-bcc09780bb9b.png)

**Comment by Govind-Jangid** [comment]
@ankush fyi
also installed at FC

**Comment by ankush** [comment]
@Govind-Jangid 

Then perhaps you need to pull latest version of frappe there. Cuz this change was done months ago.
