### ISSUE TITLE
cannot add a page

### ISSUE THREAD

**Issue by federicocalvo** [frappe/gameplan#232]
**Description**

With all type off roles, i can't add pages since i updated.

Traceback:

```Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 52, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1618, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 197, in insert
    return insert_doc(doc).as_dict()
  File "apps/frappe/frappe/client.py", line 472, in insert_doc
    return frappe.get_doc(doc).insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1097, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 925, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1288, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1270, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 922, in fn
    return method_object(*args, **kwargs)
  File "apps/gameplan/gameplan/gameplan/doctype/gp_page/gp_page.py", line 15, in on_update
    self.update_search_index()
  File "apps/gameplan/gameplan/gameplan/doctype/gp_page/gp_page.py", line 20, in update_search_index
    search.index_doc(self)
  File "apps/gameplan/gameplan/search.py", line 76, in index_doc
    self.add_document(id, fields, payload=payload)
  File "apps/gameplan/gameplan/utils/search.py", line 41, in add_document
    self.redis.ft(self.index_name).add_document(doc_id, payload=json.dumps(payload), replace=True, **mapping)
  File "env/lib/python3.10/site-packages/redis/utils.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "env/lib/python3.10/site-packages/redis/commands/search/commands.py", line 283, in add_document
    return self._add_document(
  File "env/lib/python3.10/site-packages/redis/commands/search/commands.py", line 218, in _add_document
    return self.execute_command(*args)
  File "env/lib/python3.10/site-packages/redis/client.py", line 1269, in execute_command
    return conn.retry.call_with_retry(
  File "env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "env/lib/python3.10/site-packages/redis/client.py", line 1270, in <lambda>
    lambda: self._send_command_parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 1246, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 897, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'FT.ADD', with args beginning with: '_64ebc70d9ad9d88b|gameplan_idx' '_64ebc70d9ad9d88b|search_doc:GP Page:16' '1.0' 'PAYLOAD' '{"team": "marketing", "project": 5}' ```


In Frappe Cloud
Frappe Version: b384059
Gameplan Version: 5a2eddc

**Comment by netchampfaris** [comment]
Fixed via https://github.com/frappe/gameplan/commit/50e56ef8daef73e8b29062a997138e5fc4056301
