### ISSUE TITLE
Not able to get the app without crashing frappe bench

### ISSUE THREAD

**Issue by nahiiko** [frappe/gameplan#234]
As soon as I use `bench get-app gameplan`

My Frappe Bench instance crashes (and will crash every time after that even after relaunch):

```
22:10:59 web.1            |  * Detected change in '/Users/nahiko/frappe/env/lib/python3.10/site-packages/PIL/_deprecate.py', reloading
22:10:59 web.1            |  * Restarting with stat
22:11:00 web.1            |  * Debugger is active!
22:11:55 web.1            | Traceback (most recent call last):
22:11:55 web.1            |   File "/Users/nahiko/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
22:11:55 web.1            |     return _run_code(code, main_globals, None,
22:11:55 web.1            |   File "/Users/nahiko/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
22:11:55 web.1            |     exec(code, run_globals)
22:11:55 web.1            |   File "/Users/nahiko/frappe/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
22:11:55 web.1            |     main()
22:11:55 web.1            |   File "/Users/nahiko/frappe/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
22:11:55 web.1            |     click.Group(commands=commands)(prog_name="bench")
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
22:11:55 web.1            |     return self.main(*args, **kwargs)
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
22:11:55 web.1            |     rv = self.invoke(ctx)
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
22:11:55 web.1            |     return _process_result(sub_ctx.command.invoke(sub_ctx))
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
22:11:55 web.1            |     return _process_result(sub_ctx.command.invoke(sub_ctx))
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
22:11:55 web.1            |     return ctx.invoke(self.callback, **ctx.params)
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
22:11:55 web.1            |     return __callback(*args, **kwargs)
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
22:11:55 web.1            |     return f(get_current_context(), *args, **kwargs)
22:11:55 web.1            |   File "/Users/nahiko/frappe/apps/frappe/frappe/commands/__init__.py", line 29, in _func
22:11:55 web.1            |     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
22:11:55 web.1            |   File "/Users/nahiko/frappe/apps/frappe/frappe/commands/utils.py", line 955, in serve
22:11:55 web.1            |     frappe.app.serve(
22:11:55 web.1            |   File "/Users/nahiko/frappe/apps/frappe/frappe/app.py", line 412, in serve
22:11:55 web.1            |     run_simple(
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/werkzeug/serving.py", line 1097, in run_simple
22:11:55 web.1            |     run_with_reloader(
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/werkzeug/_reloader.py", line 440, in run_with_reloader
22:11:55 web.1            |     reloader = reloader_loops[reloader_type](
22:11:55 web.1            |   File "/Users/nahiko/frappe/env/lib/python3.10/site-packages/werkzeug/_reloader.py", line 315, in __init__
22:11:55 web.1            |     from watchdog.events import EVENT_TYPE_OPENED
22:11:55 web.1            | ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/Users/nahiko/frappe/env/lib/python3.10/site-packages/watchdog/events.py)
22:11:55 system           | web.1 stopped (rc=1)
22:11:55 system           | sending SIGTERM to redis_cache.1 (pid 17754)
22:11:55 system           | sending SIGTERM to redis_socketio.1 (pid 17750)
22:11:55 system           | sending SIGTERM to redis_queue.1 (pid 17751)
22:11:55 system           | sending SIGTERM to socketio.1 (pid 17749)
22:11:55 system           | sending SIGTERM to watch.1 (pid 17748)
22:11:55 system           | sending SIGTERM to schedule.1 (pid 17753)
22:11:55 system           | sending SIGTERM to worker.1 (pid 17752)
22:11:55 redis_cache.1    | 17754:signal-handler (1688242315) Received SIGTERM scheduling shutdown...
22:11:55 redis_queue.1    | 17751:signal-handler (1688242315) Received SIGTERM scheduling shutdown...
22:11:55 redis_socketio.1 | 17750:signal-handler (1688242315) Received SIGTERM scheduling shutdown...
22:11:55 system           | worker.1 stopped (rc=-15)
22:11:55 system           | schedule.1 stopped (rc=-15)
22:11:55 system           | socketio.1 stopped (rc=-15)
22:11:55 system           | watch.1 stopped (rc=-15)
22:11:55 redis_socketio.1 | 17750:M 01 Jul 2023 22:11:55.228 # User requested shutdown...
22:11:55 redis_socketio.1 | 17750:M 01 Jul 2023 22:11:55.229 * Saving the final RDB snapshot before exiting.
22:11:55 redis_queue.1    | 17751:M 01 Jul 2023 22:11:55.231 # User requested shutdown...
22:11:55 redis_queue.1    | 17751:M 01 Jul 2023 22:11:55.231 * Saving the final RDB snapshot before exiting.
22:11:55 redis_socketio.1 | 17750:M 01 Jul 2023 22:11:55.238 * DB saved on disk
22:11:55 redis_socketio.1 | 17750:M 01 Jul 2023 22:11:55.238 * Removing the pid file.
22:11:55 redis_socketio.1 | 17750:M 01 Jul 2023 22:11:55.239 # Redis is now ready to exit, bye bye...
22:11:55 redis_cache.1    | 17754:M 01 Jul 2023 22:11:55.239 # User requested shutdown...
22:11:55 redis_cache.1    | 17754:M 01 Jul 2023 22:11:55.239 * Removing the pid file.
22:11:55 redis_cache.1    | 17754:M 01 Jul 2023 22:11:55.239 # Redis is now ready to exit, bye bye...
22:11:55 system           | redis_socketio.1 stopped (rc=0)
22:11:55 system           | redis_cache.1 stopped (rc=0)
22:11:55 redis_queue.1    | 17751:M 01 Jul 2023 22:11:55.243 * DB saved on disk
22:11:55 redis_queue.1    | 17751:M 01 Jul 2023 22:11:55.243 * Removing the pid file.
22:11:55 redis_queue.1    | 17751:M 01 Jul 2023 22:11:55.243 # Redis is now ready to exit, bye bye...
22:11:55 system           | redis_queue.1 stopped (rc=0)
```

platform: Mac M1 (I get the error even with Rosetta terminal)
I'm not even able to install through docker although with a different error ("cannot find module 'cookie')

**Comment by netchampfaris** [comment]
The error doesn't look like it's coming from gameplan's code. What is your python version? Gameplan depends on latest frappe v15 which depends on python 3.11.
