### ISSUE TITLE
Cannot add reactions to posts

### ISSUE THREAD

**Issue by michellealva** [frappe/gameplan#251]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/gameplan/gameplan/extends/client.py", line 62, in batch
    return [r.json for r in responses]
  File "apps/gameplan/gameplan/extends/client.py", line 62, in <listcomp>
    return [r.json for r in responses]
AttributeError: 'NoneType' object has no attribute 'json'
```

**Comment by huembw** [comment]
It's reproducible on some specific sites. I dont know why :((

**Comment by netchampfaris** [comment]
The original error reported by @michellealva has been fixed.

@huembw If you are facing this error, please open a new issue with the error traceback.
