### ISSUE TITLE
Getting error while installing

### ISSUE THREAD

**Issue by santagarwal** [frappe/gameplan#353]
Getting gameplan
$ git clone https://github.com/frappe/gameplan.git  --depth 1 --origin upstream
Cloning into 'gameplan'...
remote: Enumerating objects: 394, done.
remote: Counting objects: 100% (394/394), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 394 (delta 87), reused 212 (delta 78), pack-reused 0 (from 0)
Receiving objects: 100% (394/394), 2.09 MiB | 23.24 MiB/s, done.
Resolving deltas: 100% (87/87), done.
Ignoring dependencies of gameplan. To install dependencies use --resolve-deps
Installing gameplan
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/gameplan 
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21
.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11                                                                                                                             ERROR: Could not find a version that satisfies the requirement onnxruntime==1.16.2 (from gameplan) (from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2, 1.20.0, 1.20.1)
ERROR: No matching distribution found for onnxruntime==1.16.2
ERROR: /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/gameplan 
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/gameplan ' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/app.py", line 778, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/app.py", line 253, in install
    install_app(
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/app.py", line 912, in install_app
    bench.run(
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.12/site-packages/bench/utils/__init__.py", line 181, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/gameplan

**Comment by ezenkico** [comment]
Yeah I got the same issue.
Is there any way this can be upgraded to use the latest version of python?

**Comment by akshay0411** [comment]
Yeah I got the same issue.
Is there any solution? I'm using Python 3.12

**Comment by Cliffenjugush** [comment]
wycliffe@wycliffe-Lenovo-IdeaPad-L340-15API:~/frappe-benchgm$ bench get-app gameplan
Getting gameplan
$ git clone https://github.com/frappe/gameplan.git  --depth 1 --origin upstream
Cloning into 'gameplan'...
remote: Enumerating objects: 396, done.
remote: Counting objects: 100% (396/396), done.
remote: Compressing objects: 100% (322/322), done.
remote: Total 396 (delta 81), reused 246 (delta 64), pack-reused 0 (from 0)
Receiving objects: 100% (396/396), 2.51 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (81/81), done.
Ignoring dependencies of gameplan. To install dependencies use --resolve-deps
Installing gameplan
$ /home/wycliffe/frappe-benchgm/env/bin/python -m pip install --quiet --upgrade -e /home/wycliffe/frappe-benchgm/apps/gameplan 
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.16.2 (from gameplan) (from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2, 1.20.0, 1.20.1)
ERROR: No matching distribution found for onnxruntime==1.16.2
ERROR: /home/wycliffe/frappe-benchgm/env/bin/python -m pip install --quiet --upgrade -e /home/wycliffe/frappe-benchgm/apps/gameplan 
subprocess.CalledProcessError: Command '/home/wycliffe/frappe-benchgm/env/bin/python -m pip install --quiet --upgrade -e /home/wycliffe/frappe-benchgm/apps/gameplan ' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.12/dist-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/usr/local/lib/python3.12/dist-packages/bench/app.py", line 778, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.12/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bench/app.py", line 253, in install
    install_app(
  File "/usr/local/lib/python3.12/dist-packages/bench/app.py", line 912, in install_app
    bench.run(
  File "/usr/local/lib/python3.12/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bench/utils/__init__.py", line 181, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: /home/wycliffe/frappe-benchgm/env/bin/python -m pip install --quiet --upgrade -e /home/wycliffe/frappe-benchgm/apps/gameplan

**Comment by Manuel924** [comment]
## I managed to solve it ...

Once you have executed the comman `bench get app gameplan` or cloned the repository you only have to do the following:

- Open the configuration file in the following path: **`vim apps/gameplan/pyproject.toml`**.
- Find the line that says _dependencies_ and change the dependency at the end to **"onnxruntime==1.17.3"**.
- Execute the command **`bench setup requirements `**, and you will be able to install it later on your site without any problem.

I hope I helped you :)

**Comment by netchampfaris** [comment]
https://github.com/frappe/gameplan/commit/6f87647d651331a104b8b1593ca7f14757f294ad
